//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace changelog {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("changelog.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Log.
        /// </summary>
        internal static string changelog {
            get {
                return ResourceManager.GetString("changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - {0}
        ///.
        /// </summary>
        internal static string mk_entry_comment {
            get {
                return ResourceManager.GetString("mk_entry_comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ### {entry_type}
        ///{entry_comments}.
        /// </summary>
        internal static string mk_entry_section {
            get {
                return ResourceManager.GetString("mk_entry_section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## {version} - {date}
        ///{entry_section}.
        /// </summary>
        internal static string mk_entry_template {
            get {
                return ResourceManager.GetString("mk_entry_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # {changelog}
        ///{subtitle}
        ///{semver_comment}
        ///---------------------------
        ///.
        /// </summary>
        internal static string mk_template {
            get {
                return ResourceManager.GetString("mk_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to create a new changelog file? [y/n].
        /// </summary>
        internal static string prompt_createfile {
            get {
                return ResourceManager.GetString("prompt_createfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What relevant items were {0}? Each line will be an entry, hit Enter on a blank line to finish..
        /// </summary>
        internal static string prompt_entry_template {
            get {
                return ResourceManager.GetString("prompt_entry_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What format would you like? &quot;M&quot; for Markdown or &quot;T&quot; for Text. [Enter for Markdown].
        /// </summary>
        internal static string prompt_filetype {
            get {
                return ResourceManager.GetString("prompt_filetype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does this project support semantic version? [y/n].
        /// </summary>
        internal static string prompt_semver_support {
            get {
                return ResourceManager.GetString("prompt_semver_support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This project adheres to [Semantic Versioning](http://semver.org/)..
        /// </summary>
        internal static string semver_comment {
            get {
                return ResourceManager.GetString("semver_comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All notable changes to this project will be documented in this file..
        /// </summary>
        internal static string subtitle {
            get {
                return ResourceManager.GetString("subtitle", resourceCulture);
            }
        }
    }
}
